# nixpacks.toml
# This file tells Railway to install system dependencies needed for crawl4ai

[phases.setup]
nixPkgs = [
    "chromium",
    "chrome-gnome-shell",
    "gcc",
    "g++",
    "make",
    "python311Full",
    "python311Packages.pip",
    "xvfb-run"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps"
]

[start]
cmd = "streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0"